app_code: {{app_code}}
app_name: {{app_name}}
author: {{author}}
category: {{category}}
!!python/unicode 'date': '2022-12-02 16:59:34'
desktop:
  height: 720
  is_max: true
  width: 1280
introduction:
is_use_celery: True
!!python/unicode 'language': python
language_support: 中文
libraries:
{% for key, value in pkgs.items() %}
  - name: {{key}}
    version: {{value}}
{% endfor %}
version: {{version}}
container:
    memory: {{memory}}