version: '3'
services:
  postgres:
    image: postgres:14.10
    container_name: postgres-container
    environment:
      POSTGRES_DB: weops_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - /path/to/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - /path/to/redis/data:/data

  casbin-mesh:
    image: ghcr.io/casbin/casbin-mesh:latest
    container_name: casbin-mesh-container
    ports:
      - "0.0.0.0:4002:4002"
    volumes:
      - /path/to/casmesh/data:/casmesh/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak-container
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "0.0.0.0:8080:8080"
    command: start-dev

  weops-lite:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    # 覆盖dockerfile中的CMD指令
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - casbin-mesh
      - keycloak